import { beforeEach, describe, expect, it } from 'vitest'
import { mountSuspended } from '@nuxt/test-utils/runtime'
import { createPinia, setActivePinia } from 'pinia'
import StrategyChartView from '../../app/components/learn/StrategyChartView.vue'
import RuleExplorer from '../../app/components/learn/RuleExplorer.vue'
import LearnPage from '../../app/pages/learn.vue'
import { PRESETS } from '../../app/utils/engine/rules'

describe('StrategyChartView', () => {
  it('renders the generated grids and a cell detail on click', async () => {
    const w = await mountSuspended(StrategyChartView, { props: { rules: PRESETS.VEGAS_STRIP_6D! } })
    const cell = w.find('[data-testid="cell-hard-16-10"]')
    expect(cell.exists()).toBe(true)
    expect(cell.text()).toBe('H') // Vegas: no surrender → 16vT hits
    await cell.trigger('click')
    const detail = w.find('[data-testid="cell-detail"]')
    expect(detail.text()).toContain('hard 16 vs T')
    expect(detail.text()).toMatch(/-\d+\.\d%/)
  })
})

describe('RuleExplorer', () => {
  beforeEach(() => setActivePinia(createPinia()))

  it('moves the edge when H17 is toggled', async () => {
    const w = await mountSuspended(RuleExplorer)
    const before = w.find('[data-testid="explorer-edge"]').text()
    const h17 = w.findAll('input[type="checkbox"], button[role="switch"]')[0]!
    await h17.trigger('click')
    const after = w.find('[data-testid="explorer-edge"]').text()
    expect(after).not.toBe(before)
  })
})

describe('learn page', () => {
  it('mounts with the chart tab and engine-driven content', async () => {
    const w = await mountSuspended(LearnPage)
    expect(w.text()).toContain('Generated by the EV engine')
    expect(w.find('[data-testid="cell-hard-16-10"]').exists()).toBe(true)
  })
})
