<script setup lang="ts">
import { ILLUSTRIOUS_18, FAB_4 } from '~/utils/engine/counting'
import {
  TWENTY_ONE_PLUS_THREE_PAYS, LUCKY_LADIES_PAYS, MATCH_THE_DEALER_PAYS, BUSTER_PAYS
} from '~/utils/engine/sideBets'
import { PRESETS } from '~/utils/engine/rules'
import { BUCKETS, PROB, actionEVs, distFor, houseEdge } from '~/utils/engine/basicStrategy'
import type { EngineFacts } from '~/utils/learnContent'
import {
  HILO_ROWS, PROCEDURE, VARIATIONS, glossary, historyEras, myths, tidbits, viability
} from '~/utils/learnContent'

const store = useBlackjackStore()
onMounted(() => {
  if (!store.sessionActive) store.restore()
})

const activeRules = computed(() => store.settings?.rules ?? PRESETS.VEGAS_STRIP_6D!)

// ── every number below comes from the engine, never transcribed (guidelines §2.2/§4) ─────
const payoutDeltaPct = computed(() => ((houseEdge({ ...activeRules.value, blackjackPayout: '6:5' })
  - houseEdge({ ...activeRules.value, blackjackPayout: '3:2' })) * 100).toFixed(1))
const h17DeltaPct = computed(() => ((houseEdge({ ...activeRules.value, dealerHitsSoft17: true })
  - houseEdge({ ...activeRules.value, dealerHitsSoft17: false })) * 100).toFixed(1))
const dasDeltaPct = computed(() => ((houseEdge({ ...activeRules.value, doubleAfterSplit: false })
  - houseEdge({ ...activeRules.value, doubleAfterSplit: true })) * 100).toFixed(2))
const dealerBustPct = computed(() => Math.round(
  BUCKETS.reduce((s, up) => s + PROB[up] * distFor(up, activeRules.value).bust, 0) * 100))
const sixteenVsTen = computed(() => {
  const evs = actionEVs({ total: 16, soft: false, twoCards: true, fromSplit: false }, 10, activeRules.value)
  return { standLoss: Math.round(-evs.stand * 100), hitLoss: Math.round(-evs.hit * 100) }
})

const tabs = [
  { label: 'Strategy chart', value: 'chart' },
  { label: 'Rules lab', value: 'rules' },
  { label: 'Counting', value: 'counting' },
  { label: 'Side bets', value: 'sidebets' },
  { label: 'History', value: 'history' },
  { label: 'Myths', value: 'myths' },
  { label: 'Procedure', value: 'procedure' },
  { label: 'Glossary', value: 'glossary' }
]
const tab = ref('chart')

/** Engine-derived figures the content interpolates — computed above, never transcribed. */
const facts = computed<EngineFacts>(() => ({
  payoutDeltaPct: payoutDeltaPct.value,
  h17DeltaPct: h17DeltaPct.value,
  dasDeltaPct: dasDeltaPct.value,
  dealerBustPct: dealerBustPct.value,
  sixteenVsTen: sixteenVsTen.value
}))

// the prose lives in ~/utils/learnContent — this page is structure, not copy
const HISTORY_ERAS = computed(() => historyEras(facts.value))
const VIABILITY = computed(() => viability(facts.value))
const TIDBITS = computed(() => tidbits(facts.value))
const MYTHS = computed(() => myths(facts.value))
const GLOSSARY = computed(() => glossary(facts.value))

const DEVIATIONS = [...ILLUSTRIOUS_18, ...FAB_4]

const SIDEBET_TABLES = [
  { name: '21+3 (MA §28(f) / AC Xtreme)', pays: TWENTY_ONE_PLUS_THREE_PAYS },
  { name: 'Lucky Ladies (MA §24)', pays: LUCKY_LADIES_PAYS },
  { name: 'Buster Blackjack (MA §27)', pays: BUSTER_PAYS }
]
const MTD = MATCH_THE_DEALER_PAYS
</script>

<template>
  <main class="mx-auto w-full max-w-3xl flex-1 space-y-4 overflow-y-auto p-4 pb-10">
    <h1 class="pt-2 text-xl font-bold text-[var(--accent-cream)]">
      Learn
    </h1>
    <UTabs
      v-model="tab"
      :items="tabs"
      :content="false"
    />

    <section v-if="tab === 'chart'">
      <p class="mb-3 text-xs text-neutral-400">
        Generated by the EV engine for <span class="font-semibold">{{ activeRules.name }}</span> — tap any cell for the math.
      </p>
      <StrategyChartView :rules="activeRules" />
    </section>

    <section v-else-if="tab === 'rules'">
      <RuleExplorer />
    </section>

    <section
      v-else-if="tab === 'counting'"
      class="space-y-3 text-sm text-neutral-300"
    >
      <h2 class="font-semibold text-[var(--accent-cream)]">
        Hi-Lo in three steps
      </h2>
      <table class="text-xs font-mono">
        <tbody>
          <tr
            v-for="row in HILO_ROWS"
            :key="row.tag"
          >
            <td class="pr-4 text-neutral-400">
              {{ row.cards }}
            </td>
            <td :class="row.value > 0 ? 'text-emerald-400' : row.value < 0 ? 'text-red-400' : 'text-neutral-400'">
              {{ row.tag }}
            </td>
          </tr>
        </tbody>
      </table>
      <p class="text-xs text-neutral-400">
        1) Add the tag of every card you see. 2) Divide by decks remaining (estimate the discard tray
        to the nearest half deck) — that's the true count. 3) Each true-count point above +1 is worth
        roughly half a percent to you. Example: RC +9 with 3 decks left → TC +3 → ≈1% player edge.
      </p>
      <h2 class="pt-2 font-semibold text-[var(--accent-cream)]">
        Deviations (advanced)
      </h2>
      <p class="text-xs text-neutral-400">
        The Illustrious 18 + Fab 4 — the only departures from basic strategy worth memorizing first. Insurance at TC ≥ +3 is the single most valuable line.
      </p>
      <table
        class="w-full text-xs"
        data-testid="deviation-table"
      >
        <thead>
          <tr class="text-left text-neutral-400">
            <th class="py-1">
              Play
            </th><th>Threshold</th><th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="dev in DEVIATIONS"
            :key="dev.id"
            class="border-t border-neutral-800 text-neutral-300"
          >
            <td class="py-1">
              {{ dev.description }}
            </td>
            <td class="font-mono">
              {{ dev.minTrueCount !== undefined ? `TC ≥ ${dev.minTrueCount}` : `TC < ${dev.maxTrueCount}` }}
            </td>
            <td class="capitalize">
              {{ dev.play.replace('-', ' ') }}
            </td>
          </tr>
        </tbody>
      </table>
    </section>

    <section
      v-else-if="tab === 'sidebets'"
      class="space-y-4 text-sm"
    >
      <UAlert
        color="warning"
        variant="soft"
        title="Every table below is the official pay schedule — and every one of these bets costs several times the main game's edge."
        description="Track what they actually cost you on the Analysis page ledger."
      />
      <div
        v-for="table in SIDEBET_TABLES"
        :key="table.name"
      >
        <h2 class="font-semibold text-[var(--accent-cream)]">
          {{ table.name }}
        </h2>
        <table class="mt-1 w-full text-xs text-neutral-300">
          <tbody>
            <tr
              v-for="(pays, variant) in table.pays"
              :key="variant"
              class="border-t border-neutral-800 align-top"
            >
              <td class="py-1 pr-3 font-mono text-neutral-400">
                {{ variant }}
              </td>
              <td class="py-1">
                <span
                  v-for="(mult, outcome) in pays"
                  :key="outcome"
                  class="mr-3 inline-block"
                >{{ outcome }} <span class="font-mono text-[var(--accent-gold)]">{{ mult }}:1</span></span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
        <h2 class="font-semibold text-[var(--accent-cream)]">
          Match the Dealer (MA §23, deck-dependent)
        </h2>
        <table class="mt-1 w-full text-xs text-neutral-300">
          <tbody>
            <tr
              v-for="(pays, decks) in MTD"
              :key="decks"
              class="border-t border-neutral-800"
            >
              <td class="py-1 pr-3 font-mono text-neutral-400">
                {{ decks }} decks
              </td>
              <td class="py-1">
                <span
                  v-for="(mult, tier) in pays"
                  :key="tier"
                  class="mr-3 inline-block"
                >{{ tier }} <span class="font-mono text-[var(--accent-gold)]">{{ mult }}:1</span></span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section
      v-else-if="tab === 'history'"
      class="space-y-4"
      data-testid="history-section"
    >
      <p class="text-xs text-neutral-400">
        Four centuries from a Seville card hustle to the six-deck shoe — the short, source-honest
        version. The full essay lives in the project README.
      </p>
      <ol class="space-y-3">
        <li
          v-for="item in HISTORY_ERAS"
          :key="item.era"
          class="rounded-lg border border-neutral-800 bg-neutral-900/60 p-3"
        >
          <p class="font-mono text-xs text-[var(--accent-gold)]">
            {{ item.era }}
          </p>
          <h2 class="mt-0.5 text-sm font-semibold text-[var(--accent-cream)]">
            {{ item.title }}
          </h2>
          <p class="mt-1 text-xs leading-relaxed text-neutral-300">
            {{ item.body }}
          </p>
        </li>
      </ol>

      <div
        class="rounded-lg border border-[var(--accent-gold)]/30 bg-neutral-900/60 p-3"
        data-testid="counting-viability"
      >
        <h2 class="text-sm font-semibold text-[var(--accent-gold)]">
          Is counting still viable?
        </h2>
        <p class="mt-1 text-xs leading-relaxed text-neutral-300">
          {{ VIABILITY.intro }}
        </p>
        <ul class="mt-2 space-y-1.5 text-xs text-neutral-300">
          <li
            v-for="killer in VIABILITY.killers"
            :key="killer.name"
          >
            <span class="font-semibold text-[var(--accent-cream)]">{{ killer.name }}.</span>
            {{ killer.text }}
          </li>
        </ul>
        <p class="mt-2 text-xs leading-relaxed text-neutral-300">
          {{ VIABILITY.bottomLine }}
        </p>
      </div>

      <h2 class="pt-2 text-sm font-semibold text-[var(--accent-cream)]">
        Variations you'll meet on a real floor
      </h2>
      <table class="w-full text-xs">
        <thead>
          <tr class="text-left text-neutral-400">
            <th class="py-1 pr-3">
              Variation
            </th>
            <th class="py-1 pr-3">
              The twist
            </th>
            <th class="py-1">
              The catch
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="variation in VARIATIONS"
            :key="variation.name"
            class="border-t border-neutral-800 align-top text-neutral-300"
          >
            <td class="py-1.5 pr-3 font-semibold whitespace-nowrap">
              {{ variation.name }}
            </td>
            <td class="py-1.5 pr-3">
              {{ variation.twist }}
            </td>
            <td class="py-1.5 text-neutral-400">
              {{ variation.catch }}
            </td>
          </tr>
        </tbody>
      </table>
      <p class="text-xs text-neutral-400">
        The rule of thumb: every flashy rule is paid for somewhere else on the felt — toggle any
        of them in the Rules lab and watch the edge move.
      </p>

      <h2 class="pt-2 text-sm font-semibold text-[var(--accent-cream)]">
        Tidbits
      </h2>
      <ul class="list-disc space-y-1.5 pl-5 text-xs text-neutral-300">
        <li
          v-for="tidbit in TIDBITS"
          :key="tidbit"
        >
          {{ tidbit }}
        </li>
      </ul>
    </section>

    <section
      v-else-if="tab === 'myths'"
      class="grid gap-3 sm:grid-cols-2"
    >
      <div
        v-for="myth in MYTHS"
        :key="myth.title"
        class="rounded-lg border border-neutral-800 bg-neutral-900/60 p-3"
      >
        <h2 class="text-sm font-semibold text-[var(--accent-cream)]">
          {{ myth.title }}
        </h2>
        <p class="mt-1 text-xs italic text-neutral-400">
          {{ myth.claim }}
        </p>
        <p class="mt-1 text-xs text-neutral-300">
          {{ myth.truth }}
        </p>
      </div>
    </section>

    <section
      v-else-if="tab === 'procedure'"
      class="space-y-2"
    >
      <ol class="space-y-2">
        <li
          v-for="(item, i) in PROCEDURE"
          :key="item.step"
          class="rounded-lg border border-neutral-800 bg-neutral-900/60 p-3 text-sm"
        >
          <span class="font-semibold text-[var(--accent-gold)]">{{ i + 1 }}. {{ item.step }}</span>
          <p class="mt-0.5 text-xs text-neutral-400">
            {{ item.text }}
          </p>
        </li>
      </ol>
      <p class="text-[11px] text-neutral-400">
        Sources: 205 CMR (Massachusetts), Bally's AC gaming guide, WA Gambling Commission rules — all in <code>docs/</code>.
      </p>
    </section>

    <section
      v-else
      class="text-sm"
    >
      <dl class="space-y-2">
        <div
          v-for="[term, def] in GLOSSARY"
          :key="term"
          class="rounded-lg border border-neutral-800 bg-neutral-900/60 p-2.5"
        >
          <dt class="text-xs font-semibold text-[var(--accent-cream)]">
            {{ term }}
          </dt>
          <dd class="mt-0.5 text-xs text-neutral-400">
            {{ def }}
          </dd>
        </div>
      </dl>
    </section>
  </main>
</template>
